version: 2.1

orbs:
  architect: giantswarm/architect@4.6.0

workflows:
  build:
    jobs:
      # Ensure that for every commit
      # there is an app version in the test catalog.
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-api-control-plane"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-aws-app-collection
          context: architect
          app_name: "cluster-api-control-plane"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-to-app-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
