apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-cert
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate-controlplane-cluster-x-k8s-io-v1alpha3-kubeadmcontrolplane
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.kubeadmcontrolplane.controlplane.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubeadmcontrolplanes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-cert
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-webhook
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-controlplane-cluster-x-k8s-io-v1alpha3-kubeadmcontrolplane
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubeadmcontrolplanes
  sideEffects: None
